packages:
  - 'packages/**'
  - 'tmp-packages-dir/**'
  - '!**/node-lib-starter-exclude'
# 设置为 false 时，workspace: 协议仍然有效
link-workspace-packages: true
# prefer-workspace-packages​: false
shared-workspace-lockfile: true
